# CMake generated Testfile for 
# Source directory: /home/farkasau/git/threadmaxx/tests
# Build directory: /home/farkasau/git/threadmaxx/build-werror/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[entity_storage_test]=] "/home/farkasau/git/threadmaxx/build-werror/tests/entity_storage_test")
set_tests_properties([=[entity_storage_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;55;add_test;/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;0;")
add_test([=[command_buffer_test]=] "/home/farkasau/git/threadmaxx/build-werror/tests/command_buffer_test")
set_tests_properties([=[command_buffer_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;55;add_test;/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;0;")
add_test([=[job_system_test]=] "/home/farkasau/git/threadmaxx/build-werror/tests/job_system_test")
set_tests_properties([=[job_system_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;55;add_test;/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;0;")
add_test([=[determinism_test]=] "/home/farkasau/git/threadmaxx/build-werror/tests/determinism_test")
set_tests_properties([=[determinism_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;55;add_test;/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;0;")
add_test([=[stats_test]=] "/home/farkasau/git/threadmaxx/build-werror/tests/stats_test")
set_tests_properties([=[stats_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;55;add_test;/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;0;")
add_test([=[system_stats_test]=] "/home/farkasau/git/threadmaxx/build-werror/tests/system_stats_test")
set_tests_properties([=[system_stats_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;55;add_test;/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;0;")
add_test([=[query_test]=] "/home/farkasau/git/threadmaxx/build-werror/tests/query_test")
set_tests_properties([=[query_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;55;add_test;/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;0;")
add_test([=[alpha_test]=] "/home/farkasau/git/threadmaxx/build-werror/tests/alpha_test")
set_tests_properties([=[alpha_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;55;add_test;/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;0;")
add_test([=[parallel_systems_test]=] "/home/farkasau/git/threadmaxx/build-werror/tests/parallel_systems_test")
set_tests_properties([=[parallel_systems_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;55;add_test;/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;0;")
add_test([=[acceleration_test]=] "/home/farkasau/git/threadmaxx/build-werror/tests/acceleration_test")
set_tests_properties([=[acceleration_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;55;add_test;/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;0;")
add_test([=[resource_registry_test]=] "/home/farkasau/git/threadmaxx/build-werror/tests/resource_registry_test")
set_tests_properties([=[resource_registry_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;55;add_test;/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;0;")
add_test([=[component_mask_test]=] "/home/farkasau/git/threadmaxx/build-werror/tests/component_mask_test")
set_tests_properties([=[component_mask_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;55;add_test;/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;0;")
add_test([=[hierarchy_test]=] "/home/farkasau/git/threadmaxx/build-werror/tests/hierarchy_test")
set_tests_properties([=[hierarchy_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;55;add_test;/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;0;")
add_test([=[job_system_stress_test]=] "/home/farkasau/git/threadmaxx/build-werror/tests/job_system_stress_test")
set_tests_properties([=[job_system_stress_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;55;add_test;/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;0;")
add_test([=[lifecycle_hooks_test]=] "/home/farkasau/git/threadmaxx/build-werror/tests/lifecycle_hooks_test")
set_tests_properties([=[lifecycle_hooks_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;55;add_test;/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;0;")
add_test([=[scratch_arena_test]=] "/home/farkasau/git/threadmaxx/build-werror/tests/scratch_arena_test")
set_tests_properties([=[scratch_arena_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;55;add_test;/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;0;")
add_test([=[event_channel_test]=] "/home/farkasau/git/threadmaxx/build-werror/tests/event_channel_test")
set_tests_properties([=[event_channel_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;55;add_test;/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;0;")
add_test([=[pause_timescale_test]=] "/home/farkasau/git/threadmaxx/build-werror/tests/pause_timescale_test")
set_tests_properties([=[pause_timescale_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;55;add_test;/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;0;")
add_test([=[reserved_handle_test]=] "/home/farkasau/git/threadmaxx/build-werror/tests/reserved_handle_test")
set_tests_properties([=[reserved_handle_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;55;add_test;/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;0;")
add_test([=[small_wins_test]=] "/home/farkasau/git/threadmaxx/build-werror/tests/small_wins_test")
set_tests_properties([=[small_wins_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;55;add_test;/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;0;")
add_test([=[world_has_get_test]=] "/home/farkasau/git/threadmaxx/build-werror/tests/world_has_get_test")
set_tests_properties([=[world_has_get_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;55;add_test;/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;0;")
add_test([=[bundle_test]=] "/home/farkasau/git/threadmaxx/build-werror/tests/bundle_test")
set_tests_properties([=[bundle_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;55;add_test;/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;0;")
add_test([=[parent_autoderive_test]=] "/home/farkasau/git/threadmaxx/build-werror/tests/parent_autoderive_test")
set_tests_properties([=[parent_autoderive_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;55;add_test;/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;0;")
add_test([=[register_system_at_test]=] "/home/farkasau/git/threadmaxx/build-werror/tests/register_system_at_test")
set_tests_properties([=[register_system_at_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;55;add_test;/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;0;")
add_test([=[reserve_handles_batch_test]=] "/home/farkasau/git/threadmaxx/build-werror/tests/reserve_handles_batch_test")
set_tests_properties([=[reserve_handles_batch_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;55;add_test;/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;0;")
add_test([=[frame_snapshot_test]=] "/home/farkasau/git/threadmaxx/build-werror/tests/frame_snapshot_test")
set_tests_properties([=[frame_snapshot_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;55;add_test;/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;0;")
add_test([=[resource_loader_test]=] "/home/farkasau/git/threadmaxx/build-werror/tests/resource_loader_test")
set_tests_properties([=[resource_loader_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;55;add_test;/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;0;")
add_test([=[spatial_hash_test]=] "/home/farkasau/git/threadmaxx/build-werror/tests/spatial_hash_test")
set_tests_properties([=[spatial_hash_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;55;add_test;/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;0;")
add_test([=[logger_test]=] "/home/farkasau/git/threadmaxx/build-werror/tests/logger_test")
set_tests_properties([=[logger_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;55;add_test;/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;0;")
add_test([=[hierarchy_scale_test]=] "/home/farkasau/git/threadmaxx/build-werror/tests/hierarchy_scale_test")
set_tests_properties([=[hierarchy_scale_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;55;add_test;/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;0;")
add_test([=[event_subscribe_test]=] "/home/farkasau/git/threadmaxx/build-werror/tests/event_subscribe_test")
set_tests_properties([=[event_subscribe_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;55;add_test;/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;0;")
add_test([=[job_histogram_test]=] "/home/farkasau/git/threadmaxx/build-werror/tests/job_histogram_test")
set_tests_properties([=[job_histogram_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;55;add_test;/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;0;")
add_test([=[system_wait_test]=] "/home/farkasau/git/threadmaxx/build-werror/tests/system_wait_test")
set_tests_properties([=[system_wait_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;55;add_test;/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;0;")
add_test([=[chrome_trace_test]=] "/home/farkasau/git/threadmaxx/build-werror/tests/chrome_trace_test")
set_tests_properties([=[chrome_trace_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;55;add_test;/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;0;")
add_test([=[serialization_test]=] "/home/farkasau/git/threadmaxx/build-werror/tests/serialization_test")
set_tests_properties([=[serialization_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;55;add_test;/home/farkasau/git/threadmaxx/tests/CMakeLists.txt;0;")
